AllCops:
  Exclude:
    - utils/*
    - bin/*
    - doc/*
    - log/*
    - vendor/*
    - vendor/**/*
    - tmp/*

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['resource', 'describe', 'context']

Style/Copyright:
  Notice: 'Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: "# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>\n"
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: true
  VersionAdded: '0.0.2'
